export {
  polyCreateApiKey,
  polyPlaceOrder,
  polyCancelOrder,
  polyCancelAllOrders,
  polyGetOrder,
  polyGetOrders,
  polyGetOrderbook,
  polyGetPositions,
  polyGetMarket,
  polyGetPrice,
  polyStreamPrices, // deprecated alias
  polyGetTrades,
  polyGetBalance,
  polyGetMidpoint,
  polyGetSpread,
  polyGetTickSize,
  polyGetNegRisk,
} from "./handlers/index.js";

export { PolymarketClient } from "./client.js";

export type {
  PolymarketConfig,
  PlaceOrderParams,
  OrderResult,
  CancelOrderParams,
  CancelResult,
  GetOrderParams,
  OrderDetail,
  GetOrderbookParams,
  OrderbookResult,
  GetPositionsParams,
  PositionsResult,
  GetMarketParams,
  MarketResult,
  StreamPricesParams,
  PriceResult,
  ApiCredentials,
  CreateApiKeyParams,
  OrderSide,
  OrderType,
  OrderStatus,
  OpenOrder,
  GetOrdersParams,
  CancelAllOrdersParams,
  CancelAllResult,
  GetBalanceParams,
  BalanceAllowanceResult,
  GetMidpointParams,
  MidpointResult,
  GetSpreadParams,
  SpreadResult,
  GetTickSizeParams,
  TickSizeResult,
  GetNegRiskParams,
  NegRiskResult,
} from "./types.js";

export { PolymarketError } from "./types.js";
